server:
  port: 9090
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: webbeds-fliggy
  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates/
    mode: HTML5
    servlet:
      content-type: text/html
    suffix: .html

  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
#    static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

  #  redis:
#    host: localhost
#    port: 6379
#    password:
#    database: 1
#    timeout: 5000
#    jedis:
#      pool:
#        max-active: 0
#        max-idle: 10
#        max-wait: 5000
#        min-idle: 0
#  activemq:
#    broker-url: tcp://10.24.1.46:61616
#    in-memory: true
#    pool:
#      enabled: false
#      max-connections: 100
#  rabbitmq:
#    host: 127.0.0.1
#    username: guest
#    password: guest
#  jms:
#    pub-sub-domain: true
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/webbeds?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&SSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  mvc:
#    static-path-pattern: classpath:/static/js/,classpath:/templates/,classpath:/static/css/
    static-path-pattern: /templates/**,classpath:/static/js/**,classpath:/static/css/**
#    druid:
#      filter: stat
#      initial-size: 10
#      min-idle: 5
#      max-active: 20
#      max-wait: 6000
#      time-between-eviction-runs-millis: 6000
#      min-evictable-idle-time-millis: 60000
#      validation-query: SELECT 'X'
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      pool-prepared-statements: false
#      max-pool-prepared-statement-per-connection-size: 20
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.br.entity



#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql
#
#logging.level.org.springframework.boot.autoconfigure: ERROR
